# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0002_auto_20190920_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='desc',
            field=models.TextField(default='Description of item'),
        ),
    ]
