# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0003_wish_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='wish',
        ),
        migrations.AddField(
            model_name='wish',
            name='likers',
            field=models.ManyToManyField(related_name='liked_wishes', to='belt_exam.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
