# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0004_auto_20190920_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='belt_exam.User')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_wishes', to='belt_exam.Wish')),
            ],
        ),
    ]
