# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
