# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0006_wish_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='wish',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
